name: Daily Commit Automation

on:
  schedule:
    # Runs the workflow daily at 00:05 UTC
    - cron: "5 0 * * *"

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make a dummy change (e.g., update a timestamp file)
      - name: Make changes
        run: |
          echo "Last update: $(date -u)" > daily-update.txt
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f2001923@ds.study.iitm.ac.in"
          git add daily-update.txt

      # Step 3: Commit the changes
      - name: Commit changes
        run: |
          git commit -m "Automated daily update: $(date -u)" || echo "No changes to commit"

      # Step 4: Push the commit back to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
