name: Daily Repository Update

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update repository (23f2001923@ds.study.iitm.ac.in)
        run: |
          echo "Daily update: $(date)" >> update_log.txt
          git add update_log.txt
          git commit -m "Daily automated update"
          git push

