name: Test Action

on: 
  push:
    branches:
      - main  # Change this to your branch if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 23f2001923@ds.study.iitm.ac.in
        run: echo "Hello, world!"
